# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.3, 19.9.0, 20.13.1, 21.7.3, 22.2.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Log used OS
      run: uname -a
    - name: Install dependencies (all)
      run: npm install
    - name: Build
      run: npm run build
    - name: Lint
      if: ${{ matrix.node-version == '22.2.0' }}
      run: npm run lint
    - name: Run unit tests
      run: npm test
    - name: Run e2e tests
      run: npm run e2e

  sizewatcher:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npx @adobe/sizewatcher
  semantic-release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{  !contains(github.event.head_commit.message, '[ci skip]') && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 22.2.0
        uses: actions/setup-node@v1
        with:
          node-version: '22.2.0'
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
